# python run.py --config=./projects/defectoscopy/config_multiclass_baseline.yaml

general:
  exp_name: effnet-0-debug
  project_name: defectoscopy
  save_dir: output
  seed: 17
  max_epochs: 128
  batch_size: 64
  num_workers: 16 

loggers:
- target: pytorch_lightning.loggers.TensorBoardLogger
- target: clearml.Task
  params:
    project_name: ${general.project_name}
    task_name: ${general.exp_name}
    auto_connect_frameworks: True

lightning_model: denk_baseline.lightning_models.ClassificationMulticlassModel

trainer:
  target: pytorch_lightning.Trainer
  params:
    devices: [1, 2]
    max_epochs: ${general.max_epochs}
    accelerator: gpu
    precision: bf16

model:
  target: projects.defectoscopy.model.CustomModel
  params:
    model_name: efficientnet_b0
    in_chans: 2
    num_classes: 2
    pretrained: True

criterions:
- target: torch.nn.CrossEntropyLoss
  weight: 1.0
  name: ce

optimizers:
- target: torch.optim.AdamW
  params:
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    target: denk_baseline.lr_scheduler.LinearWarmupCosineAnnealingLR
    params:
      warmup_epochs: 16
      max_epochs: ${general.max_epochs}
      warmup_start_lr: 0.0001
      eta_min: 0.00001
    
metrics:
- target: torchmetrics.Precision
  name: precision
  params: &torchmetrics_params
    num_classes: 2
    task: multiclass
- target: torchmetrics.Recall
  name: recall
  params:
    <<: *torchmetrics_params
- target: torchmetrics.F1Score
  name: f1score
  params:
    <<: *torchmetrics_params

callbacks:
- target: pytorch_lightning.callbacks.LearningRateMonitor
- target: pytorch_lightning.callbacks.ModelCheckpoint
  params:
    filename: best_f1score-{epoch:03d}-{f1score_valid:3.3f}-{precision_valid:3.3f}-{recall_valid:3.3f}-{total_loss_valid:3.3f}
    monitor: f1score_valid
    mode: max
    save_top_k: 3
    save_last: false
    save_weights_only: false

datasets:
  train:
    target: projects.defectoscopy.dataset.DefectoscopyClassificationDataset
    params: &dataset_params
      defects_csv_dir: /home/raid/datasets/defectoscopy/defects
      nondefects_csv_dir: /home/raid/datasets/defectoscopy/not_defects
      window_size: 512
      min_df_size: 256
      is_train: True
      is_multiclass: True
  valid:
    target: projects.defectoscopy.dataset.DefectoscopyClassificationDataset
    params:
      <<: *dataset_params
      is_train: False

dataloaders:
  train:
    target: torch.utils.data.DataLoader
    params: &dataloader_params
      shuffle: false
      batch_size: ${general.batch_size}
      num_workers: ${general.num_workers}
      drop_last: false
      pin_memory: true
    sampler: 
      target: torch.utils.data.RandomSampler
  valid:
    target: torch.utils.data.DataLoader
    params:
      <<: *dataloader_params
    sampler: 
      target: torch.utils.data.SequentialSampler
