common:
  exp_name: test_exp
  project_name: test_proj
  save_dir: output
  seed: 17
  batch_size: 32
  num_workers: 8

lightning_model: denk_baseline.lightning_models.SegmentationBinaryModel

trainer:
  target: pytorch_lightning.Trainer
  params:
    gpus: [0]
    max_epochs: 32

model:
  target: segmentation_models_pytorch.Unet
  params:
    encoder_name: resnet18
    classes: 1
    
criterions:
- target: torch.nn.BCEWithLogitsLoss
  weight: 1.0
  name: bce

optimizers:
- target: torch.optim.Adam
  params:
    lr: 0.001
    
metrics:
- target: segmentation_models_pytorch.utils.metrics.IoU
  params:
    threshold: 0.5
  name: iou

callbacks:
- target: pytorch_lightning.callbacks.ModelCheckpoint
  params:
    filename: best-{epoch:02d}-{iou_valid:2.2f}
    monitor: iou_valid
    mode: max
    save_top_k: 1
    save_last: true
    save_weights_only: true

dataloaders:
  train:
    target: torch.utils.data.DataLoader
    params:
      shuffle: false
      batch_size: 32
      num_workers: 16
      drop_last: false
      pin_memory: true
  valid:
    target: torch.utils.data.DataLoader
    params:
      shuffle: false
      batch_size: 32
      num_workers: 16
      drop_last: false
      pin_memory: true
      
datasets:
  train:
    target: denk_baseline.datasets.SegmentationBinaryDataset
    params:
      img_h: 256
      img_w: 256
      img_format: jpg # png, tiff ...
      images_dir: path_to_train_images
      masks_dir: path_to_train_masks
  valid:
    target: denk_baseline.datasets.SegmentationBinaryDataset
    params:
      img_h: 256
      img_w: 256
      img_format: jpg
      images_dir: path_to_valid_images
      masks_dir: path_to_valid_masks

loggers:
- target: pytorch_lightning.loggers.TensorBoardLogger