common:
  gpus:
  - 0
  task: 'binary'
  seed: 17
  folds_count: null
  batch_size: 8
  num_workers: 8
  epochs: 128
  wandb: False

model:
  target: segmentation_models_pytorch.Unet
  params:
    encoder_name: resnet34
    classes: 1
    
criterions:
- target: torch.nn.BCEWithLogitsLoss
  weight: 1.0
  name: bce

optimizers:
- target: torch.optim.Adam
  params:
    lr: 0.002
  scheduler:
    target: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    params:
      warmup_epochs: 16
      max_epochs: 128
      warmup_start_lr: 0.001
    additional:
      monitor: iou_valid

metrics:
- target: segmentation_models_pytorch.utils.metrics.IoU
  params:
    threshold: 0.5
  name: iou
  use_bg: False

callbacks:
- target: pytorch_lightning.callbacks.LearningRateMonitor
- target: pytorch_lightning.callbacks.ModelCheckpoint
  params:
    filename: best-{epoch:02d}-{iou_valid:2.2f}
    monitor: iou_valid
    mode: max
    save_top_k: 1
    save_last: true

datasets:
  train:
    target: segmentation_baseline.datasets.HubmapDataset
    params:
      img_h: 1024
      img_w: 1024
      labels:
      - 0
      - 1
      images_dir: /home/user/datasets/hubmap-organ-segmentation/train_images
      masks_dir: /home/user/datasets/hubmap-organ-segmentation/train_masks
      csv_path: /home/user/datasets/hubmap-organ-segmentation/train_split.csv
  valid:
    target: segmentation_baseline.datasets.HubmapDataset
    params:
      img_h: 1024
      img_w: 1024
      labels:
      - 0
      - 1
      images_dir: /home/user/datasets/hubmap-organ-segmentation/train_images
      masks_dir: /home/user/datasets/hubmap-organ-segmentation/train_masks
      csv_path: /home/user/datasets/hubmap-organ-segmentation/valid_split.csv

# loggers:
# - target: pytorch_lightning.loggers.TensorBoardLogger