common:
  gpus:
  - 0
  task: 'binary'
  seed: 17
  folds_count: null
  batch_size: 8
  num_workers: 8
  epochs: 128
  wandb: false

model:
  target: segmentation_models_pytorch.Unet
  params:
    encoder_name: resnet34
    classes: 1
    
criterions:
# - target: segmentation_models_pytorch.losses.SoftBCEWithLogitsLoss
#   weight: 1.0
#   name: bce
# - target: segmentation_models_pytorch.losses.DiceLoss
#   params:
#     mode: binary
#   weight: 1.0
#   name: dice
- target: segmentation_models_pytorch.losses.JaccardLoss
  params:
    mode: binary
  weight: 0.2
  name: jaccard
# - target: segmentation_models_pytorch.losses.LovaszLoss
#   params:
#     mode: binary
#   weight: 0.2
#   name: lovas
# - target: segmentation_models_pytorch.losses.TverskyLoss
#   params:
#     mode: binary
#   weight: 0.2
#   name: tversky

optimizers:
- target: torch.optim.Adam
  params:
    lr: 0.002
  scheduler:
    target: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    params:
      warmup_epochs: 16
      max_epochs: 128
      warmup_start_lr: 0.001
    additional:
      monitor: dice_valid
    # target: torch.optim.lr_scheduler.ReduceLROnPlateau
    # params:
    #   mode: max
    #   factor: 0.8
    #   patience: 10
    #   min_lr: 0.00000001
    #   verbose: false
    # additional:
    #   monitor: dice_valid
    
metrics:
- target: segmentation_models_pytorch.utils.metrics.IoU
  params:
    threshold: 0.5
  name: iou
- target: segmentation_baseline.metrics.DiceCoef
  params:
    threshold: 0.5
  name: dice

callbacks:
- target: pytorch_lightning.callbacks.LearningRateMonitor
- target: pytorch_lightning.callbacks.ModelCheckpoint
  params:
    filename: best-{epoch:02d}-{iou_valid:2.2f}-{dice_valid:2.2f}
    monitor: dice_valid
    mode: max
    save_top_k: 1
    save_last: true
    save_weights_only: true

datasets:
  train:
    target: segmentation_baseline.datasets.HubmapDataset
    params:
      img_h: 1024
      img_w: 1024
      labels:
      - 0
      - 1
      images_dir: /home/user/datasets/hubmap-organ-segmentation/train_images
      masks_dir: /home/user/datasets/hubmap-organ-segmentation/train_masks
      csv_path: /home/user/datasets/hubmap-organ-segmentation/train_split.csv
  valid:
    target: segmentation_baseline.datasets.HubmapDataset
    params:
      img_h: 1024
      img_w: 1024
      labels:
      - 0
      - 1
      images_dir: /home/user/datasets/hubmap-organ-segmentation/train_images
      masks_dir: /home/user/datasets/hubmap-organ-segmentation/train_masks
      csv_path: /home/user/datasets/hubmap-organ-segmentation/valid_split.csv

# loggers:
# - target: pytorch_lightning.loggers.TensorBoardLogger